### PR TITLE
INT-688 add map[string]? submetrics

### PR DESCRIPTION
**Pull request by dtjm**

### CODE REVIEW

**Comment by Kane-Sendgrid** [comment]
we might want to add test if JSON got right namespaces and stuff?

**Comment by dtjm** [comment]
That should be handled here https://github.com/sendgrid/tagtrics/pull/3/files#diff-8e91a54d780ba23169f87d3ba8744d63R43

**Comment by Kane-Sendgrid** [comment]
cool, what about namespaces? can we test if they are coming out correctly?

**Comment by Kane-Sendgrid** [comment]
lgtm

**Pull request merged**
